# -*- coding: utf-8 -*-
"""Echo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozZ75NhuSG3jIRtVzCOudy_iN3Xn_qCi
"""

pip install streamlit groq

import streamlit as st
from groq import Groq

client = Groq(api_key="GROQ_API_KEY")

st.title("Echo")

# Store chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# User input
user_input = st.chat_input("Type your message...")

if user_input:
    # Add user message
    st.session_state.messages.append({
        "role": "user",
        "content": user_input
    })

    # Get LLM response
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=st.session_state.messages
    )

    bot_reply = response.choices[0].message.content

    # Add bot message
    st.session_state.messages.append({
        "role": "assistant",
        "content": bot_reply
    })

    st.rerun()

# After displaying bot response, add:
col1, col2 = st.columns(2)
with col1:
    if st.button("👍 Helpful"):
        # Save feedback to a CSV
        save_feedback(user_input, bot_reply, "positive")
        st.success("Feedback saved!")
with col2:
    if st.button("👎 Not Helpful"):
        save_feedback(user_input, bot_reply, "negative")
        st.warning("Feedback saved!")

# Feedback saving function
import csv
def save_feedback(prompt, response, rating):
    with open("feedback_log.csv", "a") as f:
        writer = csv.writer(f)
        writer.writerow([prompt, response, rating])